In [1]:
import tensorflow
import keras
import csv
import numpy
import matplotlib.pyplot as plot

#loading training data
X = numpy.loadtxt("Datasets/Experiment2_x.csv", delimiter=",")
Y = numpy.loadtxt("Datasets/Experiment2_y.csv", delimiter=",")

Using TensorFlow backend.


In [2]:
#homomorphic encryption parameters
private_key = 73939133
public_key = 59393339
random_integer = 2
input_power = 3
weight_power = 3

#homomorphic encryption function
def encryption(x, input_power=3):
    return (x * 10 ** input_power + private_key * random_integer) % (private_key * public_key)

#encrypting data
X = encryption(X, input_power)
print(X)

[[1.47879266e+08 1.47879266e+08 1.47878266e+08 1.47878266e+08]
 [1.47878266e+08 1.47878266e+08 1.47879266e+08 1.47879266e+08]
 [1.47879266e+08 1.47878266e+08 1.47878266e+08 1.47879266e+08]]


In [3]:
#constructing input layer
input_layer = keras.layers.Input(shape=(4, ), name='input_layer')

#constructing hidden layers
hidden_layer_1 = keras.layers.Dense_HD(1, activation = 'linear', name='hidden_layer_1', 
                                       use_bias=False, input_power=input_power, weight_power=weight_power)(input_layer)

#constructing output layer
output_layer = keras.layers.Dense(1, activation = 'sigmoid', name='output_layer')(hidden_layer_1)

#constructing the model of neural network
model = keras.models.Model(inputs=input_layer, outputs=output_layer)
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_layer (InputLayer)     (None, 4)                 0         
_________________________________________________________________
hidden_layer_1 (Dense_HD)    (None, 1)                 4         
_________________________________________________________________
output_layer (Dense)         (None, 1)                 2         
Total params: 6
Trainable params: 6
Non-trainable params: 0
_________________________________________________________________


In [4]:
#saing the weights of trained neural network
model.load_weights('Experiment2_model_weights.h5')

#showing the weights in the model of neural network
print(model.get_weights())

[array([[-0.      ],
       [ 4.912928],
       [ 4.676048],
       [-0.      ]], dtype=float32), array([[-3.699102]], dtype=float32), array([7.0296235], dtype=float32)]


In [5]:
#predicting the outputs of the model based on training data
predictions = model.predict(X) 
print(numpy.round(predictions, 1))

[[0.]
 [0.]
 [1.]]
